Feature/task2
katemalets/SFEDU pull request #3
Opened 2021-02-24 11:02 UTC by katemalets

2021-02-24 15:15 UTC, nareykov requested changes

2021-02-24 15:15 UTC, nareykov commented on AccountHandler.apxc
> +        if(accountName.length() == 0) {
String.isBlank() would be better (Returns true if the specified String is white space, empty (''), or null; otherwise, returns false.)

2021-02-25 05:55 UTC, katemalets commented on AccountHandler.apxc
> +        if(accountName.length() == 0) {
Thanks! I overwrote and added this method to class
` if(String.isBlank(accountName)) {
             return null;
         }`

2021-02-25 07:23 UTC, nareykov approved these changes

2021-02-25 07:58 UTC, closed without merging