Feature/task3
katemalets/SFEDU pull request #4
Opened 2021-02-24 11:41 UTC by katemalets

2021-02-24 15:17 UTC, nareykov requested changes
Let's create a new branch for this task to keep the only task3-related class there

2021-02-25 05:59 UTC, katemalets commented
deleted task 2 from this branch

2021-02-25 07:26 UTC, nareykov commented on ContactSearch.apxc
> +        List<Contact> contactList = [select ID, Name from Contact where (LastName = :lastName and MailingPostalCode = :mailingPostalCode)];
We prefer to write SOQL query using uppercase, like 'SELECT Id, Name FROM Contact WHERE...'

2021-02-25 07:26 UTC, nareykov approved these changes

2021-02-25 08:00 UTC, katemalets commented on ContactSearch.apxc
> +        List<Contact> contactList = [select ID, Name from Contact where (LastName = :lastName and MailingPostalCode = :mailingPostalCode)];
Got it. Will do it in future.

2021-02-25 08:00 UTC, closed without merging